version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  scheduler:
    build: .
    ports:
      - "9090:9090"
    environment:
      - REDIS_ADDRESS=redis:6379
    depends_on:
      - redis

volumes:
  redis_data: